#! /usr/bin/env ruby

args = ARGV.reverse
command = args.pop

puts "running #{command}"

case command
when 'open'
  `open dreaming/dreaming.pde`
when 'run'
  `open #{File.expand_path(File.dirname(__FILE__))}/run_sketch.app`
when 'stop'
  `echo "quit application \\"Processing\\"" | osascript`
end