#! /usr/bin/env ruby

require 'sinatra_server'

args = ARGV.reverse
command = args.pop

puts "running #{command}"

case command
when 'start'
  `launchctl load ~/Library/LaunchAgents/com.jklabs.Dreaming.plist`
when 'stop'
  `launchctl unload ~/Library/LaunchAgents/com.jklabs.Dreaming.plist`
when 'reboot'
  `echo "tell application \\"Finder\\" \n restart \n end tell" | osascript`
when 'server:start'
  SinatraServer.new.start
when 'server:stop'
  SinatraServer.new.stop
end